version: '3.8'

services:
  frontend:
    image: rmfernandezma1/basic3tier-ui:latest
    ports:
      - "3005:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: rmfernandezma1/basic3tier-api:latest
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=basic3tier;Username=postgres;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=basic3tier
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./api/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
